### ISSUE TITLE
How to change only selected  tab text color

### ISSUE THREAD

**Issue by hemant314** [Crysis21/PagerTabIndicator#3]
I need to  change the only selected tab text color with remaining tab text should be same color

**Comment by Crysis21** [comment]
I made an update to the library. Automatic text highlight is done when using basic text tabs, if you set the parameter `tab_highlight_text=true` the text color will have the indicator color. You can set a different color by also setting the param `tab_highlight_text_color` to your desired value.

Please update to version 1.0.7 to use this. 
`compile 'com.hold1:pagertabindicator:1.0.7'`

If you are using custom tab views using TabProvider interface, then you should do your own logic based on the example of `CustomAnimAdapter` in my sample app.

I also exposed a method `getTabAt(position)` in case you need a quick access to a certain tab.
