### ISSUE TITLE
Cutting Text on tab_lock_expand=true

### ISSUE THREAD

**Issue by ashishislive** [Crysis21/PagerTabIndicator#4]
The tab text is cutting not displaying properly. Similar feature available on pagerslidingtabstrip (should_expand) which is working as expected. Please fix it. This is library is very useful for me. Other than pagerslidingtabstrip library isn't working after upgrading sdk.
Alternatively can you add text typeface function?

**Comment by Crysis21** [comment]
I will check this problem today, but I think you can solve it now. By default, I set a tab padding property (which is exposed to you as a xml param `tab_padding` and method call which sets the left/right padding in each tab. The default size is 12dp, which I realize it's kinda big. Change this toa  smaller size, say 4dp and it should be ok. you can even set it to 0.

I will think about the facetype support. I though most people will use the custom view fucntionality, but it seems I was wrong.

**Comment by ashishislive** [comment]
Thanks looking forward for updates.. 😊
