### ISSUE TITLE
Comparing properties with PagerSlidingTabStrip

### ISSUE THREAD

**Issue by jverne** [Crysis21/PagerTabIndicator#6]
Without me having to dig through two codebases, is there a quick and dirty comparison between the properties between PagerSlidingTabStrip and PagerTabIndicator?

I'm trying to sort out `pstsTabBackgroundResIds` for example, and I can't quite get my tab collection to go across the entire bottom of the view.

Basically, I'm seeing if I can switch from this layout fragment:

```
<com.astuetz.PagerSlidingTabStrip
        android:id="@+id/bottombar"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        app:pstsDividerPadding="0dp"
        app:pstsIndicatorHeight="60dp"
        app:pstsIndicatorColor="@color/text_grey_500"
        app:pstsShouldExpand="true"
        app:pstsTabBackgroundResIds="@array/setting_tab_backgrounds"
        app:pstsTextAllCaps="false" />
```

**Comment by rosalein123** [comment]
This seems to be an error because I didnt add this.
