### ISSUE TITLE
Unable to find using Maven Central in Android Studio

### ISSUE THREAD

**Issue by matador0227** [Crysis21/PagerTabIndicator#9]
For some reason I'm unable to sync my Gradle with this implementation. is there anything special I need to know or understand when importing this into my android studio project? I have maven central and many other libraries, but for some reason yours 'fails to resolve'.  

implementation 'com.hold1:pagertabindicator:1.0.7'

**Comment by matador0227** [comment]
a couple more points on this. I was using jCenter until they dropped out of existence. I removed any reference to them and refreshed my Gradle dependencies to ensure everything was being pulled out of maven Central. It seems clear that the library is hosted on JCenter, and thus my grief. can you change this to be hosted with maven or google, or recommend a way for folks currently using this library to handle?

**Comment by Crysis21** [comment]
I just picked this project back. I will be updating it to kotlin, with support for `ViewPager2` and Jetpack navigation. Long overdue, but other projects kept me busy.
